print('Qingyun Li Task A')
print('Peter Oh Task A')
print('Andrew Kirk Task A')
print('Qingyun Li Task B')
print('Peter Oh Task B')
print('Andrew Kirk Task B')
print('Qingyun Li Task C')
print('Peter Oh Task C')